---
application:
  name: "simple-example-node-with-postgresql"
  project: "vas"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "asxz"
  version: "11"
routers:
- name: "main-simple-example-node-with-postgresql"
  routes:
  - application_name: "simple-example-node-with-postgresql"
    paths:
    - "/*"
